/* ═══════════════════════════════════════════════════════
   AI AGENTS — deterministic generators for the profile page
   README · Roast · Badges  (real data, no external API key)
═══════════════════════════════════════════════════════ */

const compact = (n) => {
  const num = Number(n) || 0;
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`;
  if (num >= 1000) return `${(num / 1000).toFixed(1)}k`;
  return String(num);
};

/* ─────────────────────────── README GENERATOR ─────────────────────────── */

export function generateProfileReadme(profile, stats) {
  const ov = stats?.overview || {};
  const langs = stats?.languages?.slice(0, 6) || [];
  const name = profile.name || profile.login;
  const location = profile.location || "Somewhere on Earth";
  const bio =
    profile.bio || `Building things with ${ov.topLanguage || "code"} and way too much coffee.`;
  const contact = profile.blog || profile.html_url;

  const langList = langs.length
    ? langs.map((l) => `- **${l.name}** — ${l.count} repo${l.count > 1 ? "s" : ""}`).join("\n")
    : "- *Public languages are still loading… or classified.*";

  const badges = [
    `![Followers](https://img.shields.io/badge/Followers-${compact(profile.followers)}-blue?style=flat-square&logo=github)`,
    `![Stars](https://img.shields.io/badge/Stars-${compact(ov.totalStars)}-yellow?style=flat-square&logo=github)`,
    `![Repos](https://img.shields.io/badge/Repos-${profile.public_repos}-green?style=flat-square&logo=github)`,
    `![Forks](https://img.shields.io/badge/Forks-${compact(ov.totalForks)}-orange?style=flat-square&logo=git)`,
  ].join(" ");

  return `# Hi 👋, I'm ${name}

${badges}

**${profile.login}** · ${location}

> ${bio}

## 🧰 About me
- 🔭 Currently building with **${ov.topLanguage || "everything"}**
- 📦 ${profile.public_repos} public repos · ⭐ ${compact(ov.totalStars)} stars collected
- 🚀 Shipping at roughly **${ov.repoGrowth || "a mysterious"}** pace
- 📬 ${contact}

## 🛠️ Languages & tools

${langList}

## 📈 GitHub stats

| Metric | Value |
|---|---|
| ⭐ Total stars | ${ov.totalStars} |
| 🍴 Total forks | ${ov.totalForks} |
| 🗂️ Languages used | ${ov.totalLanguagesUsed} |
| 🔥 Avg stars / repo | ${ov.avgStars} |
| 📦 Avg repo size | ${ov.avgSize} KB |

---
*Generated by GitInsight AI — because your README deserved better.*
`;
}

/* ─────────────────────────── PROFILE ROAST ─────────────────────────── */

const LANG_ROASTS = {
  JavaScript:
    "You write JavaScript. Half your commits say 'fixed it', the other half say 'fixed it for real this time'.",
  TypeScript:
    "You preach TypeScript safety but still have `any` scattered through your history like confetti.",
  Python:
    "You import libraries the way other people breathe — I'm fairly sure half your code is just `import` statements.",
  Java:
    "You're still adding `public static void main` to your nightmares, aren't you?",
  Go: "You named a language Go, but the only thing that's going is your sleep schedule.",
  Rust: "You told everyone about the borrow checker, and honestly it's the only thing that ever listens to you.",
  "C++":
    "Your code is 40% templates and 60% segfaults you pretend not to see.",
  "C#": "You've recompiled your hopes and dreams and they're still throwing exceptions.",
  Ruby: "Everything is an object, including your will to write tests.",
  PHP: "It just works, which is the single most suspicious sentence in software.",
};

const FALLBACKS = [
  "You're actually pretty decent — but don't let that get around, it would ruin the brand.",
  "Your commit messages read like a cryptogram: 'fix', 'wip', 'a', 'done'. A literal 'done'.",
  "Your profile picture is the most worked-on part of this profile.",
];

export function generateProfileRoast(profile, stats, repos, variant = 0) {
  const ov = stats?.overview || {};
  const lines = [];

  // Star hoarding
  if (ov.totalRepos > 10 && ov.totalStars < 10) {
    lines.push(
      `You've planted **${ov.totalRepos}** repositories and harvested **${ov.totalStars}** star${ov.totalStars === 1 ? "" : "s"}. The farmer's market is not impressed.`,
    );
  } else if (ov.totalStars > 1000) {
    lines.push(`Look at you flexing ${compact(ov.totalStars)} stars like anyone actually reads your code.`);
  } else if (ov.totalRepos > 0 && Number(ov.avgStars) < 1) {
    lines.push(`Your average repo gets **${ov.avgStars}** star${Number(ov.avgStars) === 1 ? "" : "s"}. I've watched paint dry with more approval.`);
  }

  // Bio
  if (!profile.bio || !profile.bio.trim()) {
    lines.push("Your bio is empty. Are you a developer or a government secret?");
  } else if (profile.bio.length > 120) {
    lines.push("Your bio is a whole novel. We get it, you're passionate — now fix those variable names.");
  }

  // Followers
  if (profile.followers < 10) {
    lines.push(`You have **${profile.followers}** follower${profile.followers === 1 ? "" : "s"}. Your commits are performing for an empty stadium.`);
  }

  // Repo count
  if (ov.totalRepos < 5) {
    lines.push(`Only **${ov.totalRepos}** public repo${ov.totalRepos === 1 ? "" : "s"}? That's not a portfolio, that's a side quest.`);
  }

  // Top language
  if (ov.topLanguage && LANG_ROASTS[ov.topLanguage]) {
    lines.push(LANG_ROASTS[ov.topLanguage]);
  }

  // Old account, thin output
  const startYear = new Date(profile.created_at).getFullYear();
  if (startYear && new Date().getFullYear() - startYear > 5 && ov.totalRepos < 20) {
    lines.push(`Account since **${startYear}** and this is the best we get? The nostalgia is doing heavy lifting.`);
  }

  // Repo description laziness
  if (repos && repos.length > 3) {
    const blank = repos.filter((r) => !r.description).length;
    if (blank >= repos.length / 2) {
      lines.push(`**${blank}/${repos.length}** of your repos have no description. The mystery is not the appeal.`);
    }
  }

  // Topology of empty repos
  if (repos && repos.length > 0) {
    const emptyRepos = repos.filter((r) => (r.stargazers_count || 0) === 0 && (r.forks_count || 0) === 0);
    if (emptyRepos.length >= repos.length / 2 && emptyRepos.length > 3) {
      lines.push(`${emptyRepos.length} of your repos have zero stars AND zero forks. They're not repos, they're storage units.`);
    }
  }

  if (lines.length < 3) lines.push(...FALLBACKS);

  // Shuffle deterministically by variant so "roast again" feels fresh
  const count = 3 + (variant % 2);
  const slice = lines.slice(0, count);
  if (variant % 2 === 1 && lines.length > count) slice.push(lines[count]);

  return slice.join("\n\n");
}

/* ─────────────────────────── BADGE GENERATOR ─────────────────────────── */

export function generateBadges(profile, stats) {
  const ov = stats?.overview || {};

  const items = [
    { label: "Followers", value: compact(profile.followers), color: "blue", logo: "github" },
    { label: "Total Stars", value: compact(ov.totalStars), color: "yellow", logo: "github" },
    { label: "Public Repos", value: String(profile.public_repos), color: "green", logo: "github" },
    { label: "Total Forks", value: compact(ov.totalForks), color: "orange", logo: "git" },
    { label: "Languages", value: String(ov.totalLanguagesUsed), color: "blueviolet", logo: "code" },
    { label: "Top Language", value: ov.topLanguage || "N/A", color: "blue", logo: "code" },
    { label: "Avg Stars", value: String(ov.avgStars), color: "brightgreen", logo: "star" },
    { label: "Repos/Month", value: String(ov.repoGrowth || "N/A"), color: "lightgrey", logo: "rocket" },
  ];

  const buildUrl = (item) => {
    const label = item.label.replace(/\s+/g, "_");
    const value = encodeURIComponent(item.value);
    return `https://img.shields.io/badge/${label}-${value}-${item.color}?style=for-the-badge&logo=${item.logo}&logoColor=white`;
  };

  const withUrls = items.map((i) => ({
    ...i,
    url: buildUrl(i),
    markdown: `![${i.label}](${buildUrl(i)})`,
  }));
  const markdown = withUrls.map((i) => i.markdown).join("\n");
  const html = withUrls.map((i) => `<img alt="${i.label}" src="${i.url}" />`).join(" ");

  return { items: withUrls, markdown, html };
}
